//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWinCsOrderAccessoriesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Employee_ID { get; set; }
        public int Order_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
